export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  USER_INACTIVE: "USER_INACTIVE",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  ROLE_IN_USE: "ROLE_IN_USE",
  AGENT_SESSION_EXPIRED: "AGENT_SESSION_EXPIRED",
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  USERNAME_EXISTS: "USERNAME_EXISTS",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
